api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "noshi-fee"
type = "function"
uid = "c0e48eeb-113d-148e-cc2e-bdbff0e32d911483e397"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
